version: "2"
services:
  elgatokeyligt2mqtt:
    container_name: elgatokeyligt2mqtt
    restart: unless-stopped
    build: .
    environment:
      - MQTT_SERVER=${MQTT_SERVER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_BASE_TOPIC=${MQTT_BASE_TOPIC}
      - DEBUG=${DEBUG}
    network_mode: host
