version: "2"
services:
  elgatokeyligt2mqtt:
    container_name: elgatokeyligt2mqtt
    restart: unless-stopped
    build: .
    environment:
      - MQTT_SERVER
      - MQTT_PORT
      - MQTT_USER
      - MQTT_PASSWORD
      - MQTT_BASE_TOPIC
    network_mode: host
